name: Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REG_RU_HOST }}
          username: ${{ secrets.REG_RU_USERNAME }}
          key: ${{ secrets.REG_RU_SSH_KEY }}
          script: |
            export SUDO_PASSWORD=${{ secrets.SUDO_PASSWORD }}
            /home/deploy_user/deploy_dma.sh
